### ISSUE TITLE
hello world

### ISSUE THREAD

**Issue by MaxChabanenko** [petrishyns/PartyMaker#2]

**Comment by IlliaMalanchuk3228** [comment]
https://www.google.com/search?q=pepe+frog&sxsrf=ALiCzsaL9c_fXFOwxttkzFG2zyTKwA3-yg:1662631490424&tbm=isch&source=iu&ictx=1&vet=1&fir=yVneuuLbmZNtqM%252CZz6JuJz3nmXtFM%252C%252Fg%252F11bxjbk7vb&usg=AI4_-kRn-o9jG6X60V3HXHFD9RVho1Mbtg&sa=X&ved=2ahUKEwjw4IP7-IT6AhVE_SoKHV24BbgQ_B16BAgFEAI#imgrc=yVneuuLbmZNtqM
